steps:
  # 1. Build the Container Image using your Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mastergrowbot-web', '.']

  # 2. Push the Image to the Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mastergrowbot-web']

  # 3. Deploy the Image to Cloud Run (This updates your Site URL)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mastergrowbot-web'   # Name of your Cloud Run Service
      - '--image'
      - 'gcr.io/$PROJECT_ID/mastergrowbot-web'
      - '--region'
      - 'us-central1'         # Standard region (adjust if yours is different)
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Makes the site public

images:
  - 'gcr.io/$PROJECT_ID/mastergrowbot-web'
