workflows:
  android-release:
    name: MasterGrowbot Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - production    # Loads Keystore
        - app_config    # Loads API Keys
      node: 20.11.1
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Web Assets
        script: |
          npm run build
      - name: Sync and Copy Capacitor
        script: |
          npx cap sync android
      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - Agcomsol@gmail.com
