# MasterGrowbot AI - CI/CD Pipeline Configuration (v1.6.4 - 2026 Edition)
workflows:
  android-release:
    name: Android Release Build 2026
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - mastergrowbot_keystore
      groups:
        - Production
      vars:
        VITE_GEMINI_API_KEY: ${GEMINI_API_KEY}
        VITE_REVENUECAT_API_KEY: ${REVENUECAT_API_KEY}
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        PACKAGE_NAME: "com.mastergrowbot.app"
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home
    scripts:
      - name: Install Dependencies
        script: |
          npm cache clean --force
          npm install --legacy-peer-deps
          npm install @capacitor/android @revenuecat/purchases-capacitor @capacitor-community/in-app-review --legacy-peer-deps
      - name: Web Build
        script: npm run build
      - name: Capacitor Sync & Deep Repair
        script: |
          # 1. Force a fresh start to recreate missing gradlew scripts
          rm -rf android
          npx cap add android
          npx cap sync android

          # 2. Inject google-services.json
          mkdir -p android/app
          cat <<EOF > android/app/google-services.json
          {
            "project_info": {
              "project_number": "360575943200",
              "project_id": "gen-lang-client-0483274603"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:360575943200:android:9d2fad05b843bffa4d3245",
                  "android_client_info": { "package_name": "com.mastergrowbot.app" }
                },
                "api_key": [ { "current_key": "AIzaSyBEmRHHbEqZvbYwgOmuk8THcxuxJSlewlg" } ]
              }
            ]
          }
          EOF

          # 3. Root build.gradle replacement (Fixed SDK & Bouncy Castle)
          cat <<EOF > android/build.gradle
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies {
                  classpath 'com.android.tools.build:gradle:8.2.1'
                  classpath 'com.google.gms:google-services:4.4.2'
              }
          }
          ext {
              compileSdkVersion = 34
              targetSdkVersion = 34
              minSdkVersion = 22
          }
          allprojects {
              repositories { google(); mavenCentral() }
              configurations.all {
                  resolutionStrategy { force 'org.bouncycastle:bcprov-jdk18on:1.77' }
              }
          }
          EOF

          # 4. Inject Firebase dependencies
          sed -i '' '/dependencies {/a \    implementation platform("com.google.firebase:firebase-bom:34.7.0")\n    implementation "com.google.firebase:firebase-analytics"' android/app/build.gradle
          grep -q "com.google.gms.google-services" android/app/build.gradle || echo 'apply plugin: "com.google.gms.google-services"' >> android/app/build.gradle

      - name: Build Android App Bundle
        script: |
          # Absolute Cache Cleanup
          rm -rf ~/.gradle/caches/
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
