workflows:
  android-release:
    name: MasterGrowbot Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - production
        - app_config
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.jks
      node: 20.11.1
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          # CRITICAL: Force clean install on the server
          rm -rf node_modules package-lock.json
          # CRITICAL: Use legacy-peer-deps to fix React 19 conflicts
          npm install --legacy-peer-deps
      
      - name: Build Web Assets
        script: |
          npm run build
      
      - name: Sync Capacitor Plugins
        script: |
          npx cap sync android
      
      - name: Decode Security Files
        script: |
          if [ -n "$CM_KEYSTORE_ENCODED" ]; then
              echo $CM_KEYSTORE_ENCODED | base64 --decode > /tmp/keystore.jks
          else
              echo "Using debug keystore (CodeMagic artifact)"
          fi

          if [ -n "$ANDROID_GOOGLE_SERVICES_JSON" ]; then
              echo $ANDROID_GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
          fi
      
      - name: Build Android App Bundle
        script: |
          cd android
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew
          ./gradlew clean bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - Agcomsol@gmail.com

  ios-app-store:
    name: MasterGrowbot iOS App Store
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - ios-config # This MUST match the group name you created
      node: 20.11.1
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: ios # Only builds on the 'ios' branch
          include: true
    scripts:
      - name: Install dependencies
        script: |
          rm -rf node_modules package-lock.json
          npm install --legacy-peer-deps
      
      - name: Build Web App
        script: |
          npm run build
          npx cap sync ios
      
      - name: Set up code signing settings on Xcode project
        script: |
          # Initialize the Keychain
          keychain initialize

          # Decode the P12 file from Env Var
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          
          # Decode the Provisioning Profile from Env Var
          echo $CM_PROVISIONING_PROFILE | base64 --decode > /tmp/provisioning_profile.mobileprovision

          # Add to Keychain
          keychain add-certificates \
            --certificate /tmp/certificate.p12 \
            --certificate-password "$CERTIFICATE_PASSWORD"

          # Apply Profile to Xcode
          xcode-project use-profiles --profile /tmp/provisioning_profile.mobileprovision

      - name: Build IPA for App Store
        script: |
          # Build the archive and IPA using the profile we just set
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --config Release \
            --archive-flags "-destination 'generic/platform=iOS'"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - "*.DS_Store"

    publishing:
      email:
        recipients:
          - Agcomsol@gmail.com
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
