workflows:
  android-release:
    name: MasterGrowbot Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - production
        - app_config
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.jks
      node: 20.11.1
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          # CRITICAL: Force clean install on the server
          rm -rf node_modules package-lock.json
          # CRITICAL: Use legacy-peer-deps to fix React 19 conflicts
          npm install --legacy-peer-deps
      
      - name: Build Web Assets
        script: |
          npm run build
      
      - name: Sync Capacitor Plugins
        script: |
          npx cap sync android
      
      - name: Decode Security Files
        script: |
          if [ -n "$CM_KEYSTORE_ENCODED" ]; then
              echo $CM_KEYSTORE_ENCODED | base64 --decode > /tmp/keystore.jks
          else
              echo "Using debug keystore (CodeMagic artifact)"
          fi

          if [ -n "$ANDROID_GOOGLE_SERVICES_JSON" ]; then
              echo $ANDROID_GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
          fi
      
      - name: Build Android App Bundle
        script: |
          cd android
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew
          ./gradlew clean bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - Agcomsol@gmail.com
