workflows:
  android-release:
    name: MasterGrowbot Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - google_play # Ensure this group exists in Codemagic with your keystore variables
      node: 20.11.1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android App Bundle
        script: |
          cd android
          chmod +x gradlew
          # Build signed release bundle
          ./gradlew bundleRelease --no-daemon
    artifacts:
      # This path tells Codemagic where to find the file to display for download
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - Agcomsol@gmail.com