workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - Production
      vars:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        REVENUECAT_API_KEY: ${REVENUECAT_API_KEY}
        PACKAGE_NAME: "com.mastergrowbot.app"
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        JAVA_TOOL_OPTIONS: "-Xmx4g"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g"
      node: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Web Build
        script: |
          npm run build
      - name: Capacitor Sync
        script: |
          rm -rf android
          npm install @capacitor/android --legacy-peer-deps
          npx cap add android
          npx cap sync android
          rm -rf ~/.gradle/caches
          echo "android.useAndroidX=true" > android/gradle.properties
          echo "android.enableJetifier=false" >> android/gradle.properties
          cd android
          ./gradlew wrapper --gradle-version 8.5 --distribution-type bin
          chmod +x gradlew
          cd ..
      - name: Set up KeyStore
        script: |
          echo $CM_KEYSTORE | base64 --decode > android/app/mastergrowbot.keystore
          cat > android/key.properties <<EOF
          storePassword=$CM_STORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=mastergrowbot.keystore
          EOF
      - name: Build Android App Bundle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: false