workflows:
  android-release:
    name: Android Release Build 2026
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - mastergrowbot_keystore
      groups:
        - Production
      vars:
        VITE_GEMINI_API_KEY: ${GEMINI_API_KEY}
        VITE_REVENUECAT_API_KEY: ${REVENUECAT_API_KEY}
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        PACKAGE_NAME: "com.mastergrowbot.app"
    scripts:
      - name: Install Dependencies
        script: |
          npm cache clean --force
          npm install --legacy-peer-deps
          npm install @capacitor/android@^6.0.0 @revenuecat/purchases-capacitor @capacitor-community/in-app-review --legacy-peer-deps
      - name: Web Build
        script: |
          npm run build
      - name: Capacitor Sync & Self-Healing Config
        script: |
          npx cap add android || true
          
          # 1. Generate root variables.gradle
          cat <<EOF > android/variables.gradle
          ext {
              minSdkVersion = 22
              compileSdkVersion = 34
              targetSdkVersion = 34
              androidxActivityVersion = '1.8.0'
              androidxAppCompatVersion = '1.6.1'
              androidxCoordinatorLayoutVersion = '1.2.0'
              androidxCoreVersion = '1.12.0'
              androidxFragmentVersion = '1.6.2'
              junitVersion = '4.13.2'
              androidxJunitVersion = '1.1.5'
              androidxEspressoCoreVersion = '3.5.1'
              cordovaAndroidVersion = '10.1.1'
          }
          EOF

          # 2. Generate root build.gradle
          cat <<EOF > android/build.gradle
          buildscript {
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath 'com.android.tools.build:gradle:8.2.1'
                  classpath 'com.google.gms:google-services:4.4.0'
              }
          }
          allprojects {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          task clean(type: Delete) {
              delete rootProject.buildDir
          }
          EOF

          # 3. Create settings.gradle with Capacitor linkages
          cat <<EOF > android/settings.gradle
          include ':app'
          project(':capacitor-android').projectDir = new File('../node_modules/@capacitor/android/capacitor')
          include ':capacitor-android'
          apply from: 'capacitor.settings.gradle'
          EOF

          # 4. Generate app-level build.gradle
          cat <<EOF > android/app/build.gradle
          apply plugin: 'com.android.application'
          apply plugin: 'com.google.gms.google-services'

          android {
              namespace "com.mastergrowbot.app"
              compileSdk 34
              defaultConfig {
                  applicationId "com.mastergrowbot.app"
                  minSdkVersion 22
                  targetSdkVersion 34
                  versionCode 1
                  versionName "1.0"
                  testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
              }
              buildTypes {
                  release {
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                  }
              }
          }

          repositories {
              flatDir {
                  dirs 'libs'
              }
          }

          dependencies {
              implementation fileTree(dir: 'libs', include: ['*.jar'])
              implementation 'androidx.appcompat:appcompat:1.6.1'
              implementation project(':capacitor-android')
              implementation project(':capacitor-cordova-android-plugins')
              implementation platform('com.google.firebase:firebase-bom:34.7.0')
              implementation 'com.google.firebase:firebase-analytics'
          }

          apply from: 'capacitor.build.gradle'
          EOF
          
          npx cap sync android

      - name: Build Android App Bundle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab