workflows:
  android-release:
    name: MasterGrowbot Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - production    # Loads Keystore
        - app_config    # Loads API Keys
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.jks
      node: 20.11.1
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          rm -f package-lock.json
          # FIXED: Added --legacy-peer-deps to ignore React 19 version strictness
          npm install --legacy-peer-deps
      
      - name: Build Web Assets
        script: |
          npm run build
      
      - name: Sync Capacitor Plugins
        script: |
          npx cap sync android
      
      - name: Decode Security Files
        script: |
          # 1. DECODE KEYSTORE
          if [ -n "$CM_KEYSTORE_ENCODED" ]; then
              echo "🔐 Decoding keystore..."
              echo $CM_KEYSTORE_ENCODED | base64 --decode > /tmp/keystore.jks
          else
              echo "❌ ERROR: CM_KEYSTORE_ENCODED is missing!"
              exit 1
          fi

          # 2. DECODE GOOGLE SERVICES JSON
          if [ -n "$ANDROID_GOOGLE_SERVICES_JSON" ]; then
              echo "🔥 Decoding google-services.json..."
              echo $ANDROID_GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
              echo "✅ google-services.json injected successfully."
          else
              echo "❌ ERROR: ANDROID_GOOGLE_SERVICES_JSON is missing! App will crash."
              exit 1
          fi
      
      - name: Build Android App Bundle
        script: |
          cd android
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew
          ./gradlew clean bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - Agcomsol@gmail.com
