workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - mastergrowbot_keystore
      groups:
        - Production
      vars:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        REVENUECAT_API_KEY: ${REVENUECAT_API_KEY}
        PACKAGE_NAME: "com.mastergrowbot.app"
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home
        JAVA_TOOL_OPTIONS: "-Xmx6g"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g"
      node: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Web Build
        script: |
          npm run build
      - name: Capacitor Sync & Self-Healing File Injection
        script: |
          # 1. Start fresh to ensure sync is clean
          rm -rf android
          npm install @capacitor/android --legacy-peer-deps
          npx cap add android
          npx cap sync android

          # 2. Inject variables.gradle with Android 15 (SDK 35) specifics
          cat <<EOF > android/variables.gradle
          ext {
              minSdkVersion = 22
              compileSdkVersion = 35
              targetSdkVersion = 35
              androidxActivityVersion = '1.9.2'
              androidxAppCompatVersion = '1.7.0'
              androidxCoordinatorLayoutVersion = '1.2.0'
              androidxCoreVersion = '1.12.0'
              androidxFragmentVersion = '1.6.2'
              coreSplashScreenVersion = '1.0.1'
              androidxWebkitVersion = '1.9.0'
          }
          EOF

          # 3. Inject missing/empty app/build.gradle with standard Capacitor 6 template
          cat <<EOF > android/app/build.gradle
          apply plugin: 'com.android.application'

          android {
              namespace "${PACKAGE_NAME}"
              compileSdkVersion rootProject.ext.compileSdkVersion
              defaultConfig {
                  applicationId "${PACKAGE_NAME}"
                  minSdkVersion rootProject.ext.minSdkVersion
                  targetSdkVersion rootProject.ext.targetSdkVersion
                  versionCode 1
                  versionName "1.0"
                  testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
                  aaptOptions {
                       nocompress 'capgen'
                  }
              }
              buildTypes {
                  release {
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                      signingConfig signingConfigs.debug
                  }
              }
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_21
                  targetCompatibility JavaVersion.VERSION_21
              }
          }

          repositories {
              flatDir {
                  dirs 'libs'
              }
          }

          dependencies {
              implementation fileTree(dir: 'libs', include: ['*.jar'])
              implementation "androidx.appcompat:appcompat:\$rootProject.ext.androidxAppCompatVersion"
              implementation "androidx.coordinatorlayout:coordinatorlayout:\$rootProject.ext.androidxCoordinatorLayoutVersion"
              implementation "androidx.core:core:\$rootProject.ext.androidxCoreVersion"
              implementation "androidx.fragment:fragment:\$rootProject.ext.androidxFragmentVersion"
              implementation "androidx.core:core-splashscreen:\$rootProject.ext.coreSplashScreenVersion"
              implementation "androidx.webkit:webkit:\$rootProject.ext.androidxWebkitVersion"
              implementation project(':capacitor-android')
              implementation project(':capacitor-cordova-android-plugins')
          }

          try {
              def servicesJSON = file('google-services.json')
              if (servicesJSON.text) {
                  apply plugin: 'com.google.gms.google-services'
              }
          } catch(Exception e) {
              logger.info("google-services.json not found, skipping Google Services plugin")
          }
          EOF

          # 4. Inject missing strings.xml
          mkdir -p android/app/src/main/res/values
          cat <<EOF > android/app/src/main/res/values/strings.xml
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
              <string name="app_name">MasterGrowbot AI</string>
              <string name="title_activity_main">MasterGrowbot AI</string>
              <string name="package_name">com.mastergrowbot.app</string>
              <string name="custom_url_scheme">com.mastergrowbot.app</string>
          </resources>
          EOF

          # 5. Force Gradle Wrapper to 8.7 (fixes Multi-release JAR support)
          sed -i '' 's|distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-8.7-all.zip|' android/gradle/wrapper/gradle-wrapper.properties
          
          # 6. Global BouncyCastle resolutionStrategy injection
          printf "\nallprojects { configurations.all { resolutionStrategy.force 'org.bouncycastle:bcprov-jdk18on:1.79' } }\n" >> android/build.gradle
          
          # 7. Core properties
          echo "android.useAndroidX=true" > android/gradle.properties
          echo "android.enableJetifier=false" >> android/gradle.properties

      - name: Set up KeyStore
        script: |
          cat >> android/key.properties <<EOF
          storePassword=\$CM_KEYSTORE_PASSWORD
          keyPassword=\$CM_KEY_PASSWORD
          keyAlias=\$CM_KEY_ALIAS
          storeFile=\$CM_KEYSTORE_PATH
          EOF

      - name: Build Android App Bundle
        script: |
          # 8. Purge corrupted JAR cache
          rm -rf ~/.gradle/caches/jars-9
          
          cd android
          chmod +x gradlew
          ./gradlew --version
          ./gradlew clean
          # 9. Final build using JDK 21 and Gradle 8.7
          ./gradlew bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: false