workflows:
  android-release:
    name: MasterGrowbot Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - production    # Loads Keystore
        - app_config    # Loads API Keys
      node: 20.11.1
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          rm -f package-lock.json
          npm install
      - name: Build Web Assets
        script: |
          npm run build
      - name: Sync and Copy Capacitor
        script: |
          npx cap sync android
      - name: Build Android App Bundle (AAB)
        script: |
          cd android
          
          # Initialize Gradle
          gradle wrapper --gradle-version 8.5
          chmod +x gradlew
          ./gradlew clean

          # FIXED: Decode the REAL keystore from Codemagic Environment Variables
          if [ -n "$CM_KEYSTORE_ENCODED" ]; then
              echo "🔐 Decoding secure keystore from environment variables..."
              # Decode to the standard path expected by build.gradle
              echo $CM_KEYSTORE_ENCODED | base64 --decode > app/keystore.jks
              
              # Set the path variable so build.gradle can find it
              export CM_KEYSTORE_PATH="$PWD/app/keystore.jks"
              echo "✅ Keystore restored successfully."
          else
              echo "❌ ERROR: CM_KEYSTORE_ENCODED variable is missing in Codemagic!"
              exit 1
          fi

          # Build the Bundle
          ./gradlew bundleRelease --no-daemon --info
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - Agcomsol@gmail.com
