workflows:
  android-release:
    name: MasterGrowbot Android Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - production  # FIXED: Changed from 'google_play' to your actual group name
        - app_config  # Added to ensure your config variables are also loaded
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.jks
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm install
      
      - name: Build Web Assets
        script: |
          npm run build
      
      - name: Sync Capacitor Plugins (CRITICAL FIX)
        script: |
          npx cap sync android
      
      - name: Decode Security Files
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.jks
      
      - name: Build Android App Bundle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
