workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - mastergrowbot_keystore
      groups:
        - Production
      vars:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        REVENUECAT_API_KEY: ${REVENUECAT_API_KEY}
        PACKAGE_NAME: "com.mastergrowbot.app"
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        JAVA_TOOL_OPTIONS: "-Xmx4g"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g"
      node: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Web Build
        script: |
          npm run build
      - name: Capacitor Sync
        script: |
          rm -rf android
          npm install @capacitor/android --legacy-peer-deps
          npx cap add android
          npx cap sync android
          rm -rf ~/.gradle/caches
          # Global Resolution Strategy Fix: Injected into root build.gradle to force bcprov version across all submodules
          echo "allprojects { configurations.all { resolutionStrategy.force 'org.bouncycastle:bcprov-jdk18on:1.79' } }" >> android/build.gradle
          # Ensure Jetifier is disabled to prevent transformation of security libraries
          echo "android.useAndroidX=true" > android/gradle.properties
          echo "android.enableJetifier=false" >> android/gradle.properties
          echo "android.jetifier.ignorelist=bcprov-jdk18on" >> android/gradle.properties
          # Force upgrade to Gradle 8.7
          cd android
          ./gradlew wrapper --gradle-version 8.7 --distribution-type all
          chmod +x gradlew
          ./gradlew --version
          cd ..
      - name: Set up KeyStore
        script: |
          # Use official Codemagic environment variables for automatic signing
          cat >> android/key.properties <<EOF
          storePassword=\$CM_KEYSTORE_PASSWORD
          keyPassword=\$CM_KEY_PASSWORD
          keyAlias=\$CM_KEY_ALIAS
          storeFile=\$CM_KEYSTORE_PATH
          EOF
      - name: Build Android App Bundle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: false