workflows:
  android-release:
    name: Android Release Build 2026
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - mastergrowbot_keystore
      groups:
        - Production
      vars:
        VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
        VITE_REVENUECAT_API_KEY: ${VITE_REVENUECAT_API_KEY}
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        FIREBASE_API_KEY: ${FIREBASE_API_KEY}
        PACKAGE_NAME: "com.mastergrowbot.app"
      node: 20
      java: 21
    scripts:
      - name: Pre-build Cleanup
        script: |
          rm -rf ~/.gradle/caches/
          npm cache clean --force
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npm install @capacitor/android@^6.0.0 @revenuecat/purchases-capacitor @capacitor-community/in-app-review --legacy-peer-deps
      - name: Web Build
        script: |
          npm run build
      - name: Capacitor Sync
        script: |
          # Ensure google-services.json is in place
          cp google-services.json android/app/google-services.json || true
          npx cap sync android
      - name: Build Android App Bundle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease --no-daemon --stacktrace
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab