
workflows:
  android-release:
    name: Android Release Build 2026
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - mastergrowbot_keystore
      groups:
        - Production
      vars:
        VITE_GEMINI_API_KEY: ${GEMINI_API_KEY}
        VITE_REVENUECAT_API_KEY: ${REVENUECAT_API_KEY}
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        PACKAGE_NAME: "com.mastergrowbot.app"
      node: 20
      java: 17
    scripts:
      - name: Install Dependencies
        script: |
          npm cache clean --force
          npm install --legacy-peer-deps
          npm install @capacitor/android@^6.0.0 @revenuecat/purchases-capacitor @capacitor-community/in-app-review --legacy-peer-deps
      - name: Web Build
        script: |
          # Bakes env vars into the JS bundle via updated vite.config.ts
          npm run build
      - name: Capacitor Add & Environment Creation
        script: |
          # 1. Create Android platform
          npx cap add android || true
          
          # 2. Create variables.gradle (Fixes 'compileSdkVersion not specified' error)
          cat <<EOF > android/variables.gradle
          ext {
              minSdkVersion = 22
              compileSdkVersion = 34
              targetSdkVersion = 34
              androidxActivityVersion = '1.8.0'
              androidxAppCompatVersion = '1.6.1'
              androidxCoordinatorLayoutVersion = '1.2.0'
              androidxCoreVersion = '1.12.0'
              androidxFragmentVersion = '1.6.2'
              junitVersion = '4.13.2'
              androidxJunitVersion = '1.1.5'
              androidxEspressoCoreVersion = '3.5.1'
              cordovaAndroidVersion = '10.1.1'
          }
          EOF

          # 3. Surgical Patching: Link variables and fix namespace
          # Inject namespace for Capacitor 6 compatibility
          sed -i '' 's/android {/android {\n    namespace "com.mastergrowbot.app"/' android/app/build.gradle
          
          # 4. Overwrite root build.gradle with linked variables and Bouncy Castle fix
          cat <<EOF > android/build.gradle
          // MasterGrowbot Root Build Configuration
          apply from: "variables.gradle"
          
          buildscript {
              repositories { google(); mavenCentral() }
              dependencies {
                  classpath 'com.android.tools.build:gradle:8.2.1'
                  classpath 'com.google.gms:google-services:4.4.2'
              }
          }

          allprojects {
              repositories { google(); mavenCentral() }
              configurations.all {
                  resolutionStrategy {
                      // Force 1.77 to prevent the 1.79 JAR execution exception in plugins
                      force 'org.bouncycastle:bcprov-jdk18on:1.77'
                  }
              }
          }

          task clean(type: Delete) {
              delete rootProject.buildDir
          }
          EOF

          # 5. Inject Google Services
          mkdir -p android/app
          cat <<EOF > android/app/google-services.json
          {
            "project_info": { "project_number": "360575943200", "project_id": "gen-lang-client-0483274603", "storage_bucket": "gen-lang-client-0483274603.firebasestorage.app" },
            "client": [ {
              "client_info": { "mobilesdk_app_id": "1:360575943200:android:9d2fad05b843bffa4d3245", "android_client_info": { "package_name": "com.mastergrowbot.app" } },
              "api_key": [ { "current_key": "AIzaSyBRIK10W7TOBUqxe9YjEXlGVkk0V43Nt9o" } ],
              "services": { "appinvite_service": { "other_platform_oauth_client": [ { "client_id": "360575943200-mq17ju3a221117rgu96v7as1b4o49rq8.apps.googleusercontent.com", "client_type": 3 } ] } }
            } ],
            "configuration_version": "1"
          }
          EOF

          # 6. Capacitor Sync
          npx cap sync android

      - name: Build Android App Bundle
        script: |
          cd android
          chmod +x gradlew
          # Upgrade Wrapper for Gradle 8.5 compatibility
          ./gradlew wrapper --gradle-version 8.5 --distribution-type all
          ./gradlew bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
