workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - Production
      vars:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        REVENUECAT_API_KEY: ${REVENUECAT_API_KEY}
        PACKAGE_NAME: "com.mastergrowbot.app"
      node: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Web Build
        script: |
          npm run build
      - name: Capacitor Sync
        script: |
          npx cap sync android
      - name: Set up KeyStore
        script: |
          echo $CM_KEYSTORE | base64 --decode > android/app/mastergrowbot.keystore
          cat > android/key.properties <<EOF
          storePassword=$CM_STORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=mastergrowbot.keystore
          EOF
      - name: Build Android App Bundle
        script: |
          cd android && ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: false