workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - mastergrowbot_keystore
      groups:
        - Production
      vars:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        REVENUECAT_API_KEY: ${REVENUECAT_API_KEY}
        PACKAGE_NAME: "com.mastergrowbot.app"
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
        JAVA_TOOL_OPTIONS: "-Xmx6g"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g"
      node: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Web Build
        script: |
          npm run build
      - name: Capacitor Sync & Hardening
        script: |
          rm -rf android
          npm install @capacitor/android --legacy-peer-deps
          npx cap add android
          npx cap sync android
          
          # 1. Manually edit gradle-wrapper.properties BEFORE any gradlew commands run
          # This prevents the build from forking an older, crashing Gradle daemon
          sed -i '' 's|distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-8.7-all.zip|' android/gradle/wrapper/gradle-wrapper.properties
          
          # 2. Inject global resolutionStrategy into root build.gradle
          # This forces the correct BouncyCastle version across all sub-modules
          printf "\nallprojects { configurations.all { resolutionStrategy.force 'org.bouncycastle:bcprov-jdk18on:1.79' } }\n" >> android/build.gradle
          
          # 3. Bypass Jetifier and add ignorelist
          echo "android.useAndroidX=true" > android/gradle.properties
          echo "android.enableJetifier=false" >> android/gradle.properties
          echo "android.jetifier.ignorelist=bcprov-jdk18on" >> android/gradle.properties
      - name: Set up KeyStore
        script: |
          # Use official Codemagic environment variables for automatic signing
          cat >> android/key.properties <<EOF
          storePassword=\$CM_KEYSTORE_PASSWORD
          keyPassword=\$CM_KEY_PASSWORD
          keyAlias=\$CM_KEY_ALIAS
          storeFile=\$CM_KEYSTORE_PATH
          EOF
      - name: Build Android App Bundle
        script: |
          # 4. Purge corrupted JAR artifacts from cache
          rm -rf ~/.gradle/caches/jars-9
          
          cd android
          chmod +x gradlew
          ./gradlew --version
          ./gradlew clean
          # 5. Build with --no-daemon to ensure clean process execution
          ./gradlew bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: false