# MasterGrowbot AI - CI/CD Pipeline Configuration (v1.6.0 - 2026 Edition)
workflows:
  android-release:
    name: Android Release Build 2026
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - mastergrowbot_keystore
      groups:
        - Production
      vars:
        VITE_GEMINI_API_KEY: ${GEMINI_API_KEY}
        VITE_REVENUECAT_API_KEY: ${REVENUECAT_API_KEY}
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        PACKAGE_NAME: "com.mastergrowbot.app"
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-21.jdk/Contents/Home
        JAVA_TOOL_OPTIONS: "-Xmx6g"
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g"
      node: latest
    scripts:
      - name: Install Dependencies
        script: |
          npm cache clean --force
          npm install --legacy-peer-deps
          npm install @capacitor/android @revenuecat/purchases-capacitor @capacitor-community/in-app-review --legacy-peer-deps
      - name: Web Build
        script: |
          npm run build
      - name: Capacitor Sync & Buildscript Injection
        script: |
          # 1. Ensure android project is present and synced
          npx cap add android || true
          npx cap sync android

          # 2. Inject google-services.json
          mkdir -p android/app
          cat <<EOF > android/app/google-services.json
          {
            "project_info": {
              "project_number": "360575943200",
              "project_id": "gen-lang-client-0483274603",
              "storage_bucket": "gen-lang-client-0483274603.firebasestorage.app"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:360575943200:android:9d2fad05b843bffa4d3245",
                  "android_client_info": { "package_name": "com.mastergrowbot.app" }
                },
                "oauth_client": [
                  {
                    "client_id": "360575943200-mq17ju3a221117rgu96v7as1b4o49rq8.apps.googleusercontent.com",
                    "client_type": 3
                  }
                ],
                "api_key": [ { "current_key": "AIzaSyBRIK10W7TOBUqxe9YjEXlGVkk0V43Nt9o" } ],
                "services": {
                  "appinvite_service": {
                    "other_platform_oauth_client": [
                      { "client_id": "360575943200-mq17ju3a221117rgu96v7as1b4o49rq8.apps.googleusercontent.com", "client_type": 3 }
                    ]
                  }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF

          # 3. Inject classpath via sed into root build.gradle
          # Using sed to find the first dependencies block and append the classpath
          sed -i '' '/dependencies {/a \        classpath "com.google.gms:google-services:4.4.2"' android/build.gradle

          # 4. Inject Firebase BoM and apply plugin in app/build.gradle
          # Add dependencies
          sed -i '' '/dependencies {/a \    implementation platform("com.google.firebase:firebase-bom:34.7.0")\n    implementation "com.google.firebase:firebase-analytics"' android/app/build.gradle
          
          # Append apply plugin to the very bottom
          echo 'apply plugin: "com.google.gms.google-services"' >> android/app/build.gradle

          # 5. Overwrite AndroidManifest.xml with mandatory permissions
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.INTERNET" />
              <uses-permission android:name="com.android.vending.BILLING" />
              <uses-permission android:name="android.permission.CAMERA" />
              <uses-permission android:name="android.permission.RECORD_AUDIO" />
              <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/AppTheme">

                  <activity
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
                      android:name=".MainActivity"
                      android:label="@string/title_activity_main"
                      android:theme="@style/AppTheme.NoActionBarLaunch"
                      android:launchMode="singleTop"
                      android:exported="true">

                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>

                      <intent-filter>
                          <action android:name="android.intent.action.VIEW" />
                          <category android:name="android.intent.category.DEFAULT" />
                          <category android:name="android.intent.category.BROWSABLE" />
                          <data android:scheme="mastergrowbot" android:host="callback" />
                      </intent-filter>

                  </activity>

                  <provider
                      android:name="androidx.core.content.FileProvider"
                      android:authorities="\${applicationId}.fileprovider"
                      android:exported="false"
                      android:grantUriPermissions="true">
                      <meta-data
                          android:name="android.support.FILE_PROVIDER_PATHS"
                          android:resource="@xml/file_paths"></meta-data>
                  </provider>
              </application>
          </manifest>
          EOF

      - name: Set up KeyStore
        script: |
          cat >> android/key.properties <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF

      - name: Build Android App Bundle
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: false